SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD := $(shell pwd)
ROOT := $(abspath $(PWD)/..)

VERILOG_SOURCES += $(ROOT)/rtl/gated_delta_step.v
TOPLEVEL := gated_delta_step
COCOTB_TEST_MODULES := test_gated_delta
SIM_BUILD := sim_build_delta_d4

ifeq ($(SIM),verilator)
EXTRA_ARGS += --timescale 1ns/1ps -Wno-fatal -Wno-WIDTH -Wno-SELRANGE
endif

include $(shell cocotb-config --makefiles)/Makefile.sim
