SIM ?= verilator
TOPLEVEL_LANG ?= verilog
PWD := $(shell pwd)
ROOT := $(abspath $(PWD)/..)
VERILOG_SOURCES += $(ROOT)/rtl/add_tree_bal.v
VERILOG_SOURCES += $(ROOT)/rtl/rsqrt_lut.v
VERILOG_SOURCES += $(ROOT)/rtl/inv_rsqrt.v
VERILOG_SOURCES += $(ROOT)/rtl/rmsnorm.v
VERILOG_SOURCES += $(ROOT)/rtl/rmsnorm8.v
TOPLEVEL := rmsnorm8
COCOTB_TEST_MODULES := test_rmsnorm_fast
SIM_BUILD := sim_build_rmsnorm_fast
ifeq ($(SIM),verilator)
EXTRA_ARGS += --timescale 1ns/1ps -Wno-fatal -Wno-WIDTH -Wno-SELRANGE
endif
include $(shell cocotb-config --makefiles)/Makefile.sim
