SIM ?= verilator
TOPLEVEL_LANG ?= verilog
PWD := $(shell pwd)
ROOT := $(abspath $(PWD)/..)
VERILOG_SOURCES += $(ROOT)/rtl/attn_decode.v
TOPLEVEL := attn_decode
COCOTB_TEST_MODULES := test_attn_decode
SIM_BUILD := sim_build_attn_decode
ifeq ($(SIM),verilator)
EXTRA_ARGS += --timescale 1ns/1ps -Wno-fatal -Wno-WIDTH -Wno-SELRANGE
endif
include $(shell cocotb-config --makefiles)/Makefile.sim
